class Reviewer < Formula
  # cite Dolzhenko_2022: "https://doi.org/10.1186/s13059-022-02851-3"
  desc "Visualize alignments in repeat regions from ExpansionHunter output"
  homepage "https://github.com/Illumina/REViewer"
  url "https://github.com/Illumina/REViewer/archive/refs/tags/v0.2.7.tar.gz"
  sha256 "8411c40028907b0294b1899cd20af6934325796da160511b649044ecf9a5169f"
  license "Apache-2.0"

  bottle do
    root_url "https://ghcr.io/v2/brewsci/bio"
    sha256 cellar: :any, arm64_tahoe:   "4fbec038295e23a0e07717423d797195466fb2d4be806a0bfde921cbbfae16fe"
    sha256 cellar: :any, arm64_sequoia: "525752187029969122f8ed6ca4b38e02990972c92545a752b7efd81e5fb89231"
    sha256 cellar: :any, arm64_sonoma:  "47ac10f5d1fac68428114ee94721333e21a6253273b9021db50b43ea09c66ae4"
    sha256 cellar: :any, x86_64_linux:  "fa67c0df052ba77694547ac13c4033142852e12b389ae2759dab6840de54f4ea"
  end

  depends_on "cmake" => :build

  depends_on "boost"
  depends_on "curl"
  depends_on "fmt"
  depends_on "htslib"
  depends_on "spdlog"
  depends_on "xz"

  uses_from_macos "bzip2"
  uses_from_macos "zlib"

  def install
    # The top-level CMakeLists.txt fetches every dependency (htslib, Boost,
    # spdlog, Catch2) over the network via ExternalProject, which fails in the
    # Homebrew sandbox. Build the inner `reviewer` project directly against the
    # Homebrew-provided libraries instead.
    inner = buildpath/"reviewer"
    graphtools = inner/"thirdparty/graph-tools"

    # Modern Boost/spdlog headers require C++17; the project pins C++11.
    inreplace inner/"CMakeLists.txt", "set(CMAKE_CXX_STANDARD 11)",
              "set(CMAKE_CXX_STANDARD 17)"
    inreplace graphtools/"CMakeLists.txt", "set(CMAKE_CXX_STANDARD 11)",
              "set(CMAKE_CXX_STANDARD 17)"

    # Boost dropped the header-only "system" component long ago; recent Boost
    # no longer ships a CMake config for it.
    inreplace inner/"CMakeLists.txt",
              "find_package(Boost 1.73 REQUIRED COMPONENTS program_options filesystem system)",
              "find_package(Boost 1.73 REQUIRED COMPONENTS program_options filesystem)"
    inreplace graphtools/"CMakeLists.txt",
              "find_package(Boost 1.5 COMPONENTS program_options filesystem system REQUIRED)",
              "find_package(Boost 1.5 COMPONENTS program_options filesystem REQUIRED)"

    # Drop -Werror (and -pedantic): the bundled nlohmann/json headers emit
    # deprecation warnings under modern clang that are not fatal here.
    inreplace graphtools/"CMakeLists.txt", " -Wall -Werror -pedantic ", " -Wall "

    # GraphCoordinates.cpp uses std::numeric_limits without including <limits>;
    # libc++ pulls it in transitively but gcc (Linux) does not.
    inreplace graphtools/"src/graphcore/GraphCoordinates.cpp",
              "#include <cassert>", "#include <cassert>\n#include <limits>"

    # Prefer the shared htslib: the static archive does not pull in libdeflate.
    inreplace inner/"CMakeLists.txt",
              "find_library(htslib libhts.a)\nfind_library(htslib hts)",
              "find_library(htslib hts)"

    # Catch2 is only needed by the UnitTests target, which we do not build.
    # Drop the find_package and the Catch2 linkage so configuration succeeds
    # without Catch2 present (the unbuilt UnitTests target is left in place).
    inreplace inner/"CMakeLists.txt", "find_package(Catch2 REQUIRED)\n", ""
    inreplace inner/"CMakeLists.txt",
              "target_link_libraries(UnitTests SnpCalling Catch2::Catch2)",
              "target_link_libraries(UnitTests SnpCalling)"

    # Homebrew's spdlog is built against an external fmt, so the REViewer
    # target must link both (the project never links the spdlog it finds).
    inreplace inner/"CMakeLists.txt",
              "        BZip2::BZip2\n        Threads::Threads)",
              "        BZip2::BZip2\n        Threads::Threads\n        spdlog::spdlog\n        fmt::fmt)"

    prefix_path = %w[boost spdlog fmt htslib xz curl]
                  .map { |f| formula_opt_prefix(f) }.join(";")

    # Core/Metrics include spdlog and htslib headers without linking their
    # targets, so surface those include dirs (and htslib's lib dir) globally.
    cxx_flags = %w[htslib spdlog fmt].map { |f| "-I#{formula_opt_include(f)}" }.join(" ")

    args = %W[
      -DCMAKE_PREFIX_PATH=#{prefix_path}
      -DCMAKE_LIBRARY_PATH=#{formula_opt_lib("htslib")}
      -DCMAKE_CXX_FLAGS=#{cxx_flags}
      -DCMAKE_POLICY_DEFAULT_CMP0167=OLD
    ]

    system "cmake", "-S", "reviewer", "-B", "build", *args, *std_cmake_args
    system "cmake", "--build", "build", "--target", "REViewer"

    bin.install "build/REViewer"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/REViewer --version 2>&1")
    assert_match "BAMlet generated by ExpansionHunter",
                 shell_output("#{bin}/REViewer --help 2>&1")
  end
end
